### ISSUE TITLE
Can't start LSP because command "clangd.applyFix" already exists

### ISSUE THREAD

**Issue by sam20908** [clangd/vscode-clangd#115]
Please describe the problem.
For some reason, when opening a file that clangd parsed for a while, it causes this issue. Sorry for the lack of information, but it happens at random.

The closest issue I can find related to this is here: https://github.com/microsoft/vscode-languageserver-node/issues/333

**Logs**
```
I[16:04:02.410] Ubuntu clangd version 11.0.1-++20201103062930+ef4ffcafbb2-1~exp1~20201103053545.129
I[16:04:02.410] PID: 1777
I[16:04:02.419] Working directory: /home/sames/Projects/matrixpp
I[16:04:02.419] argv[0]: /usr/bin/clangd
I[16:04:02.419] Starting LSP over stdin/stdout
I[16:04:02.777] <-- initialize(0)
I[16:04:02.777] Client supports legacy semanticHighlights notification and standard semanticTokens request, choosing the latter (no notifications).
I[16:04:03.059] --> reply:initialize(0) 282 ms
I[16:04:03.843] <-- initialized
I[16:04:03.843] <-- textDocument/didOpen
I[16:04:03.851] Loaded compilation database from /home/sames/Projects/matrixpp
I[16:04:03.851] --> window/workDoneProgress/create(0)
I[16:04:03.851] Enqueueing 3 commands for indexing
I[16:04:03.851] ASTWorker building file /home/sames/Projects/matrixpp/test/performance_test/determinant/test.cpp version 1 with command 
[/home/sames/Projects/matrixpp/build]
/usr/bin/g++-10 --driver-mode=g++ -I../include -isystem ../vcpkg/installed/x64-linux/include -O3 -DNDEBUG -std=c++2a -o test/performance_test/CMakeFiles/determinant.dir/determinant/test.cpp.o -c /home/sames/Projects/matrixpp/test/performance_test/determinant/test.cpp -fsyntax-only -resource-dir=/usr/lib/llvm-11/lib/clang/11.0.1
I[16:04:03.923] <-- reply(0)
I[16:04:03.924] --> $/progress
I[16:04:03.924] --> $/progress
I[16:04:04.030] <-- textDocument/documentSymbol(1)
I[16:04:04.030] <-- textDocument/codeAction(2)
I[16:04:04.030] <-- textDocument/documentLink(3)
I[16:04:04.097] --> textDocument/clangd.fileStatus
I[16:04:04.135] <-- $/cancelRequest
I[16:04:04.135] <-- textDocument/documentLink(4)
I[16:04:04.293] --> $/progress
I[16:04:04.293] --> $/progress
I[16:04:04.343] <-- textDocument/semanticTokens/full(5)
I[16:04:05.752] <-- $/cancelRequest
I[16:04:05.752] <-- textDocument/documentSymbol(6)
I[16:04:06.375] <-- $/cancelRequest
I[16:04:06.375] <-- textDocument/documentSymbol(7)
I[16:04:06.474] <-- $/cancelRequest
I[16:04:06.474] <-- textDocument/documentSymbol(8)
I[16:04:08.621] --> textDocument/publishDiagnostics
I[16:04:08.621] --> reply:textDocument/documentSymbol(1) 4591 ms, error: Task was cancelled.
I[16:04:08.623] --> reply:textDocument/codeAction(2) 4593 ms
I[16:04:08.623] --> reply:textDocument/documentLink(3) 4593 ms, error: Task was cancelled.
I[16:04:08.623] --> reply:textDocument/documentLink(4) 4488 ms
I[16:04:08.624] --> reply:textDocument/semanticTokens/full(5) 4281 ms
I[16:04:08.625] --> reply:textDocument/documentSymbol(6) 2872 ms, error: Task was cancelled.
I[16:04:08.625] --> reply:textDocument/documentSymbol(7) 2249 ms, error: Task was cancelled.
I[16:04:08.625] --> reply:textDocument/documentSymbol(8) 2151 ms
I[16:04:08.625] --> textDocument/clangd.fileStatus
I[16:04:08.716] <-- $/cancelRequest
I[16:04:08.716] <-- textDocument/codeAction(9)
I[16:04:08.716] --> reply:textDocument/codeAction(9) 0 ms
I[16:04:08.716] --> textDocument/clangd.fileStatus
I[16:04:09.026] <-- textDocument/codeAction(10)
I[16:04:09.043] --> reply:textDocument/codeAction(10) 16 ms
I[16:04:09.043] --> textDocument/clangd.fileStatus
I[16:04:09.134] <-- shutdown(11)
I[16:04:09.134] --> reply:shutdown(11) 0 ms
I[16:04:09.137] <-- exit
I[16:04:09.137] LSP finished, exiting with status 0
I[16:04:09.184] Ubuntu clangd version 11.0.1-++20201103062930+ef4ffcafbb2-1~exp1~20201103053545.129
I[16:04:09.184] PID: 1856
I[16:04:09.186] Working directory: /home/sames/Projects/matrixpp
I[16:04:09.186] argv[0]: /usr/bin/clangd
I[16:04:09.186] Starting LSP over stdin/stdout
I[16:04:09.189] <-- initialize(0)
I[16:04:09.189] Client supports legacy semanticHighlights notification and standard semanticTokens request, choosing the latter (no notifications).
I[16:04:09.349] --> reply:initialize(0) 160 ms
I[16:04:09.407] <-- shutdown(1)
I[16:04:09.407] --> reply:shutdown(1) 0 ms
I[16:04:09.426] <-- initialized
I[16:04:09.426] <-- textDocument/didOpen
I[16:04:09.431] Loaded compilation database from /home/sames/Projects/matrixpp
I[16:04:09.431] --> window/workDoneProgress/create(0)
I[16:04:09.431] Enqueueing 3 commands for indexing
I[16:04:09.432] ASTWorker building file /home/sames/Projects/matrixpp/test/performance_test/determinant/test.cpp version 1 with command 
[/home/sames/Projects/matrixpp/build]
/usr/bin/g++-10 --driver-mode=g++ -I../include -isystem ../vcpkg/installed/x64-linux/include -O3 -DNDEBUG -std=c++2a -o test/performance_test/CMakeFiles/determinant.dir/determinant/test.cpp.o -c /home/sames/Projects/matrixpp/test/performance_test/determinant/test.cpp -fsyntax-only -resource-dir=/usr/lib/llvm-11/lib/clang/11.0.1
I[16:04:09.445] <-- exit
I[16:04:09.445] LSP finished, exiting with status 0
I[16:04:09.504] Ubuntu clangd version 11.0.1-++20201103062930+ef4ffcafbb2-1~exp1~20201103053545.129
I[16:04:09.504] PID: 1865
I[16:04:09.505] Working directory: /home/sames/Projects/matrixpp
I[16:04:09.505] argv[0]: /usr/bin/clangd
I[16:04:09.505] Starting LSP over stdin/stdout
I[16:04:09.507] <-- initialize(0)
I[16:04:09.507] Client supports legacy semanticHighlights notification and standard semanticTokens request, choosing the latter (no notifications).
I[16:04:09.584] --> reply:initialize(0) 76 ms
[Error - 4:04:09 PM] Server initialization failed.
Error: command 'clangd.applyFix' already exists
	at _.registerCommand (/home/sames/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:722:448)
	at Object.registerCommand (/home/sames/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:1018:336)
	at ExecuteCommandFeature.register (/home/sames/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.8/node_modules/vscode-languageclient/lib/common/client.js:1651:53)
	at ExecuteCommandFeature.initialize (/home/sames/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.8/node_modules/vscode-languageclient/lib/common/client.js:1631:14)
	at ClangdLanguageClient.initializeFeatures (/home/sames/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.8/node_modules/vscode-languageclient/lib/common/client.js:2466:21)
	at /home/sames/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.8/node_modules/vscode-languageclient/lib/common/client.js:2150:18
[Error - 4:04:09 PM] Starting client failed
Error: command 'clangd.applyFix' already exists
	at _.registerCommand (/home/sames/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:722:448)
	at Object.registerCommand (/home/sames/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe8f/out/vs/server/remoteExtensionHostProcess.js:1018:336)
	at ExecuteCommandFeature.register (/home/sames/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.8/node_modules/vscode-languageclient/lib/common/client.js:1651:53)
	at ExecuteCommandFeature.initialize (/home/sames/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.8/node_modules/vscode-languageclient/lib/common/client.js:1631:14)
	at ClangdLanguageClient.initializeFeatures (/home/sames/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.8/node_modules/vscode-languageclient/lib/common/client.js:2466:21)
	at /home/sames/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.8/node_modules/vscode-languageclient/lib/common/client.js:2150:18
I[16:04:09.591] <-- initialized
I[16:04:09.591] <-- textDocument/didOpen
I[16:04:09.592] <-- shutdown(1)
I[16:04:09.592] --> reply:shutdown(1) 0 ms
I[16:04:09.593] <-- exit
I[16:04:09.593] LSP finished, exiting with status 0
I[16:04:09.595] Loaded compilation database from /home/sames/Projects/matrixpp
I[16:04:09.595] --> window/workDoneProgress/create(0)
I[16:04:09.595] Enqueueing 3 commands for indexing
I[16:04:09.595] ASTWorker building file /home/sames/Projects/matrixpp/test/performance_test/determinant/test.cpp version 1 with command 
[/home/sames/Projects/matrixpp/build]
/usr/bin/g++-10 --driver-mode=g++ -I../include -isystem ../vcpkg/installed/x64-linux/include -O3 -DNDEBUG -std=c++2a -o test/performance_test/CMakeFiles/determinant.dir/determinant/test.cpp.o -c /home/sames/Projects/matrixpp/test/performance_test/determinant/test.cpp -fsyntax-only -resource-dir=/usr/lib/llvm-11/lib/clang/11.0.1
```

**System information**
Clangd version (from the log, or `clangd --version`): 11.0.1-++20201103062930+ef4ffcafbb2-1~exp1~20201103053545.129
clangd extension version: v0.1.8
Operating system: Windows WSL 2

**Comment by njames93** [comment]
This sounds like it could be related to #98. Are you using the feature where clangd restarts itself when you change the compile_commands.json? If so that has been fixed but not released yet.

**Comment by sam20908** [comment]
@njames93 Ah yes I did have that setting on! Good to know that the fix has been implemented.

Can you give an estimate of when that fix will be released?

**Comment by njames93** [comment]
Can't give an estimate, for now just turn the setting off. I have a feeling that setting may get deprecated soon now that clangd is almost able to got reload the database https://reviews.llvm.org/D92663

**Comment by hokein** [comment]
The fix (debounce) is released in v0.1.9.

**Comment by lewisl** [comment]
Still breaks in 
```
Apple clangd version 14.0.3 (clang-1403.0.22.14.1)
Features: mac+xpc
Platform: x86_64-apple-darwin22.4.0; target=arm64-apple-darwin22.4.0
```

**Comment by HighCommander4** [comment]
> Still breaks in
> 
> ```
> Apple clangd version 14.0.3 (clang-1403.0.22.14.1)
> Features: mac+xpc
> Platform: x86_64-apple-darwin22.4.0; target=arm64-apple-darwin22.4.0
> ```

Can you file a new issue please, and include clangd logs and your vscode-clangd plugin version?

**Comment by burningsoulll** [comment]
I met the same problem.

**System information**
Clangd version: clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520)
clangd extension version: v0.1.24
codelldb extension version: v1.10.0
Operating system: Windows WSL 2, ubuntu20.04

**LOG**

```
I[21:12:45.383] --> reply:initialize(0) 11 ms
V[21:12:45.383] >>> {
  "id": 0,
  "jsonrpc": "2.0",
  "result": {
    "capabilities": {
      "astProvider": true,
      "callHierarchyProvider": true,
      "clangdInlayHintsProvider": true,
      "codeActionProvider": {
        "codeActionKinds": [
          "quickfix",
          "refactor",
          "info"
        ]
      },
      "compilationDatabase": {
        "automaticReload": true
      },
      "completionProvider": {
        "resolveProvider": false,
        "triggerCharacters": [
          ".",
          "<",
          ">",
          ":",
          "\"",
          "/",
          "*"
        ]
      },
      "declarationProvider": true,
      "definitionProvider": true,
      "documentFormattingProvider": true,
      "documentHighlightProvider": true,
      "documentLinkProvider": {
        "resolveProvider": false
      },
      "documentOnTypeFormattingProvider": {
        "firstTriggerCharacter": "\n",
        "moreTriggerCharacter": []
      },
      "documentRangeFormattingProvider": true,
      "documentSymbolProvider": true,
      "executeCommandProvider": {
        "commands": [
          "clangd.applyFix",
          "clangd.applyTweak"
        ]
      },
      "foldingRangeProvider": true,
      "hoverProvider": true,
      "implementationProvider": true,
      "inlayHintProvider": true,
      "memoryUsageProvider": true,
      "referencesProvider": true,
      "renameProvider": {
        "prepareProvider": true
      },
      "selectionRangeProvider": true,
      "semanticTokensProvider": {
        "full": {
          "delta": true
        },
        "legend": {
          "tokenModifiers": [
            "declaration",
            "definition",
            "deprecated",
            "deduced",
            "readonly",
            "static",
            "abstract",
            "virtual",
            "dependentName",
            "defaultLibrary",
            "usedAsMutableReference",
            "usedAsMutablePointer",
            "constructorOrDestructor",
            "userDefined",
            "functionScope",
            "classScope",
            "fileScope",
            "globalScope"
          ],
          "tokenTypes": [
            "variable",
            "variable",
            "parameter",
            "function",
            "method",
            "function",
            "property",
            "variable",
            "class",
            "interface",
            "enum",
            "enumMember",
            "type",
            "type",
            "unknown",
            "namespace",
            "typeParameter",
            "concept",
            "type",
            "macro",
            "modifier",
            "operator",
            "comment"
          ]
        },
        "range": false
      },
      "signatureHelpProvider": {
        "triggerCharacters": [
          "(",
          ")",
          "{",
          "}",
          "<",
          ">",
          ","
        ]
      },
      "standardTypeHierarchyProvider": true,
      "textDocumentSync": {
        "change": 2,
        "openClose": true,
        "save": true
      },
      "typeDefinitionProvider": true,
      "typeHierarchyProvider": true,
      "workspaceSymbolProvider": true
    },
    "serverInfo": {
      "name": "clangd",
      "version": "clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520) linux+grpc x86_64-unknown-linux-gnu"
    }
  }
}

[Error - 9:12:45 PM] Server initialization failed.
Error: command 'clangd.applyFix' already exists
	at e.$vL.registerCommand (/home/shiyao/.vscode-server/bin/2ccd690cbff1569e4a83d7c43d45101f817401dc/out/vs/workbench/api/node/extensionHostProcess.js:100:62663)
	at Object.registerCommand (/home/shiyao/.vscode-server/bin/2ccd690cbff1569e4a83d7c43d45101f817401dc/out/vs/workbench/api/node/extensionHostProcess.js:118:20174)
	at x1.register (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:37:71984)
	at x1.initialize (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:37:71547)
	at ff.initializeFeatures (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:19266)
	at ff.doInitialize (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:7616)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async ff.start (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:4636)
[Error - 9:12:45 PM] Clang Language Server client: couldn't create connection to server.
Error: command 'clangd.applyFix' already exists
	at e.$vL.registerCommand (/home/shiyao/.vscode-server/bin/2ccd690cbff1569e4a83d7c43d45101f817401dc/out/vs/workbench/api/node/extensionHostProcess.js:100:62663)
	at Object.registerCommand (/home/shiyao/.vscode-server/bin/2ccd690cbff1569e4a83d7c43d45101f817401dc/out/vs/workbench/api/node/extensionHostProcess.js:118:20174)
	at x1.register (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:37:71984)
	at x1.initialize (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:37:71547)
	at ff.initializeFeatures (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:19266)
	at ff.doInitialize (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:7616)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async ff.start (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:4636)
V[21:12:45.385] <<< {
  "jsonrpc": "2.0",
  "method": "initialized",
  "params": {}
}

I[21:12:45.385] <-- initialized
V[21:12:45.390] <<< {
  "jsonrpc": "2.0",
  "method": "initialized",
  "params": {}
}

I[21:12:45.390] <-- initialized
V[21:12:45.405] <<< {
  "id": 1,
  "jsonrpc": "2.0",
  "method": "shutdown"
}

I[21:12:45.406] <-- shutdown(1)
I[21:12:45.406] --> reply:shutdown(1) 0 ms
V[21:12:45.406] >>> {
  "id": 1,
  "jsonrpc": "2.0",
  "result": null
}

V[21:12:45.406] <<< {
  "jsonrpc": "2.0",
  "method": "exit"
}

I[21:12:45.406] <-- exit
I[21:12:45.406] LSP finished, exiting with status 0
```
