### ISSUE TITLE
"Failed to check for clangd update: TypeError: Invalid comparator: Features:" error when running "clangd: Check for language server update"

### ISSUE THREAD

**Issue by HighCommander4** [clangd/vscode-clangd#396]
When I try to run the command "clangd: Check for language server update", I get the following error in a popup:

> Failed to check for clangd update: TypeError: Invalid comparator: Features:

The stack trace in the devtools console (not that it seems very helpful) is:

```
[Extension Host] Failed to check for clangd update:  TypeError: Invalid comparator: Features:
	at va.parse (/home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.22/out/bundle.js:1:26723)
	at new Comparator (/home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.22/out/bundle.js:1:26522)
	at /home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.22/out/bundle.js:1:22500
	at Array.map (<anonymous>)
	at On.parseRange (/home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.22/out/bundle.js:1:22493)
	at /home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.22/out/bundle.js:1:21392
	at Array.map (<anonymous>)
	at new Range (/home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.22/out/bundle.js:1:21380)
	at new Range (/home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.22/out/bundle.js:1:21169)
	at outside (/home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.22/out/bundle.js:1:29670)
	at Object.gtr (/home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.22/out/bundle.js:1:30279)
	at rangeGreater (/home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.22/out/bundle.js:237:639)
	at Object.<anonymous> (/home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.22/out/bundle.js:236:3851)
	at Generator.next (<anonymous>)
	at fulfilled (/home/nr/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.22/out/bundle.js:235:39174)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by HighCommander4** [comment]
The call that's throwing is [this](https://github.com/clangd/node-clangd/blob/7eb64a179c43938b9a74659a5674b7a5e32150f0/src/index.ts#L320) `rangeGreater(releasedVer, installedVer)` call.

Going into it, we have:

```
> releasedVer.raw
'15.0.1'
> installedVer.raw
'16.0.0
Features:'
```

I'm guessing that `Features:` shouldn't be there?

**Comment by HighCommander4** [comment]
While debugging this, I discovered that vscode-clangd is not picking up the latest code in node-clangd -- rather, it is picking up the latest node-clangd _release_, 0.1.4, which does not contain some fixes such as [this one](https://github.com/clangd/node-clangd/commit/fd4795ca8be8d0eea953ed1e8b11e2bc98349991), which may fix this (as well as #384).

Filed https://github.com/clangd/node-clangd/issues/18 to release a new version of node-clangd so vscode-clangd can pick up the fixes.

**Comment by HighCommander4** [comment]
I figured out how to get vscode-clangd to consume the latest node-clangd locally, and confirmed that this bug still exists with the latest node-clangd.

**Comment by HighCommander4** [comment]
Proposed fix at https://github.com/clangd/node-clangd/pull/21
