### ISSUE TITLE
Frequent crashing in 0.1.6

### ISSUE THREAD

**Issue by jackgerrits** [clangd/vscode-clangd#41]
Please describe the problem.
After updating to 0.1.6 I get frequent crashes. I am able to restart the extension and it works for a while before stopping again.

**Logs**
```
[Error - 11:11:08 AM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:74:35)
	at ClangdLanguageClient.handleConnectionClosed (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at ClangdLanguageClient.handleConnectionClosed (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageWriter.fireClose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 11:11:08 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:74:35)
	at ClangdLanguageClient.handleConnectionClosed (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at ClangdLanguageClient.handleConnectionClosed (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageWriter.fireClose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 11:11:08 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:74:35)
	at ClangdLanguageClient.handleConnectionClosed (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at ClangdLanguageClient.handleConnectionClosed (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageWriter.fireClose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 11:11:08 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:74:35)
	at ClangdLanguageClient.handleConnectionClosed (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at ClangdLanguageClient.handleConnectionClosed (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageWriter.fireClose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 11:11:08 AM] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:74:35)
	at ClangdLanguageClient.handleConnectionClosed (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at ClangdLanguageClient.handleConnectionClosed (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageWriter.fireClose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 11:11:08 AM] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:74:35)
	at ClangdLanguageClient.handleConnectionClosed (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at ClangdLanguageClient.handleConnectionClosed (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageWriter.fireClose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
[Error - 11:11:08 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/main.js:904:25)
	at Object.dispose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:74:35)
	at ClangdLanguageClient.handleConnectionClosed (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:2309:42)
	at ClangdLanguageClient.handleConnectionClosed (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-languageclient/lib/client.js:2296:18)
	at CallbackList.invoke (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at closeHandler (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/main.js:240:26)
	at CallbackList.invoke (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/events.js:121:36)
	at StreamMessageWriter.fireClose (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/messageWriter.js:39:27)
	at Socket.<anonymous> (/home/jack/.vscode/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.6/node_modules/vscode-jsonrpc/lib/messageWriter.js:58:46)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
```

**System information**
Clangd version (from the log, or `clangd --version`): `clangd version 10.0.0 (https://github.com/llvm/llvm-project d32170dbd5b0d54436537b6b75beaf44324e0c28)`
clangd extension version: `0.1.6`
Operating system: `Ubuntu 20.04`

**Comment by sam-mccall** [comment]
Those logs don't show the original error - if you're able to reproduce the problem, is there any chance you could capture the last page or two of output before/after the first javascript stacktrace?

@hokein FYI - no idea if this is actually the 0.16 release or just a clangd bug coinciding with it...

**Comment by jackgerrits** [comment]
After downgrading to 0.1.5 and then upgrading again to 0.1.6 I can't get the original issue to repro. If I hit this again I'll reopen the issue with a more complete log. Thanks for your quick reply by the way.
