### ISSUE TITLE
"clangd: restart language server" results in `Error: command 'clangd.applyFix' already exists` if clangd isn't started yet

### ISSUE THREAD

**Issue by ToBoMi** [clangd/vscode-clangd#502]
When I restart clangd I get the following error as two notifications and also as log entry.

**Logs**
Please attach the clangd log from the "Output" window if you can.

<details>

<summary>clangd extension logs from just the restart</summary>

```
I[11:41:39.338] clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520)
I[11:41:39.338] Features: windows+grpc
I[11:41:39.338] PID: 12944
I[11:41:39.338] Working directory: [OMITTED BY ISSUE REPORTER]
I[11:41:39.338] argv[0]: c:\Users\deboeto\AppData\Roaming\Code\User\globalStorage\llvm-vs-code-extensions.vscode-clangd\install\16.0.2\clangd_16.0.2\bin\clangd.exe
I[11:41:39.338] argv[1]: --query-driver=C:\DevApps\build-support\gcc-arm-none-eabi-11\bin\arm-none-eabi-c++.exe
I[11:41:39.345] Starting LSP over stdin/stdout
I[11:41:39.346] <-- initialize(0)
I[11:41:39.374] --> reply:initialize(0) 28 ms
[Error - 11:41:39 AM] Server initialization failed.
Error: command 'clangd.applyFix' already exists
	at e.$vL.registerCommand (c:\Users\deboeto\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:62663)
	at Object.registerCommand (c:\Users\deboeto\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:20174)
	at x1.register (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:37:71984)
	at x1.initialize (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:37:71547)
	at ff.initializeFeatures (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:39:19266)
	at ff.doInitialize (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:39:7616)
	at async ff.start (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:39:4636)
[Error - 11:41:39 AM] Clang Language Server client: couldn't create connection to server.
Error: command 'clangd.applyFix' already exists
	at e.$vL.registerCommand (c:\Users\deboeto\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:62663)
	at Object.registerCommand (c:\Users\deboeto\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:20174)
	at x1.register (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:37:71984)
	at x1.initialize (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:37:71547)
	at ff.initializeFeatures (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:39:19266)
	at ff.doInitialize (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:39:7616)
	at async ff.start (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:39:4636)
[Error - 11:41:39 AM] Sending notification textDocument/didOpen failed.
Error: command 'clangd.applyFix' already exists
	at e.$vL.registerCommand (c:\Users\deboeto\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:62663)
	at Object.registerCommand (c:\Users\deboeto\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:20174)
	at x1.register (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:37:71984)
	at x1.initialize (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:37:71547)
	at ff.initializeFeatures (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:39:19266)
	at ff.doInitialize (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:39:7616)
	at async ff.start (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:39:4636)
[Error - 11:41:39 AM] Sending document notification textDocument/didOpen failed
Error: command 'clangd.applyFix' already exists
	at e.$vL.registerCommand (c:\Users\deboeto\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:99:62663)
	at Object.registerCommand (c:\Users\deboeto\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:117:20174)
	at x1.register (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:37:71984)
	at x1.initialize (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:37:71547)
	at ff.initializeFeatures (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:39:19266)
	at ff.doInitialize (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:39:7616)
	at async ff.start (c:\Users\deboeto\.vscode\extensions\llvm-vs-code-extensions.vscode-clangd-0.1.24\out\bundle.js:39:4636)
I[11:41:39.375] <-- initialized
I[11:41:39.378] <-- shutdown(1)
I[11:41:39.379] --> reply:shutdown(1) 0 ms
I[11:41:39.379] <-- exit
I[11:41:39.379] LSP finished, exiting with status 0
I[11:41:39.380] <-- textDocument/documentSymbol(22)
I[11:41:39.382] --> reply:textDocument/documentSymbol(22) 2 ms
I[11:41:39.382] --> textDocument/clangd.fileStatus
I[11:41:39.383] <-- textDocument/codeAction(23)
I[11:41:39.383] --> reply:textDocument/codeAction(23) 0 ms
I[11:41:39.383] --> textDocument/clangd.fileStatus
I[11:41:39.391] <-- textDocument/codeAction(24)
I[11:41:39.391] --> reply:textDocument/codeAction(24) 0 ms
I[11:41:39.391] --> textDocument/clangd.fileStatus
I[11:41:39.393] <-- textDocument/documentSymbol(25)
I[11:41:39.393] <-- textDocument/documentSymbol(26)
I[11:41:39.393] --> reply:textDocument/documentSymbol(25) 0 ms
I[11:41:39.393] --> reply:textDocument/documentSymbol(26) 0 ms
I[11:41:39.394] --> textDocument/clangd.fileStatus
I[11:41:39.421] <-- textDocument/documentLink(27)
I[11:41:39.422] --> reply:textDocument/documentLink(27) 0 ms
I[11:41:39.422] --> textDocument/clangd.fileStatus
I[11:42:11.318] <-- textDocument/didClose
I[11:42:11.318] --> textDocument/publishDiagnostics
```

</details>

**System information**
Clangd version (from the log, or `clangd --version`):  clangd version 16.0.2
clangd extension version: clangd v0.1.24
Operating system: Windows 10

I write this issue in relation to https://github.com/clangd/vscode-clangd/issues/115#issuecomment-1500748876

**edit**: This only happens when clangd is not started (no source code file is open) and the server is restarted. A better error message would be helpful, like "Cannot restart server, it is not started yet (Open a source file to start it)"

**Comment by HighCommander4** [comment]
https://github.com/clangd/vscode-clangd/issues/94 is related

**Comment by burningsoulll** [comment]
I met the same problem.

**System information**
Clangd version: clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520)
clangd extension version: v0.1.24
codelldb extension version: v1.10.0
Operating system: Windows WSL 2, ubuntu20.04

**LOG**

```
I[21:12:45.383] --> reply:initialize(0) 11 ms
V[21:12:45.383] >>> {
  "id": 0,
  "jsonrpc": "2.0",
  "result": {
    "capabilities": {
      "astProvider": true,
      "callHierarchyProvider": true,
      "clangdInlayHintsProvider": true,
      "codeActionProvider": {
        "codeActionKinds": [
          "quickfix",
          "refactor",
          "info"
        ]
      },
      "compilationDatabase": {
        "automaticReload": true
      },
      "completionProvider": {
        "resolveProvider": false,
        "triggerCharacters": [
          ".",
          "<",
          ">",
          ":",
          "\"",
          "/",
          "*"
        ]
      },
      "declarationProvider": true,
      "definitionProvider": true,
      "documentFormattingProvider": true,
      "documentHighlightProvider": true,
      "documentLinkProvider": {
        "resolveProvider": false
      },
      "documentOnTypeFormattingProvider": {
        "firstTriggerCharacter": "\n",
        "moreTriggerCharacter": []
      },
      "documentRangeFormattingProvider": true,
      "documentSymbolProvider": true,
      "executeCommandProvider": {
        "commands": [
          "clangd.applyFix",
          "clangd.applyTweak"
        ]
      },
      "foldingRangeProvider": true,
      "hoverProvider": true,
      "implementationProvider": true,
      "inlayHintProvider": true,
      "memoryUsageProvider": true,
      "referencesProvider": true,
      "renameProvider": {
        "prepareProvider": true
      },
      "selectionRangeProvider": true,
      "semanticTokensProvider": {
        "full": {
          "delta": true
        },
        "legend": {
          "tokenModifiers": [
            "declaration",
            "definition",
            "deprecated",
            "deduced",
            "readonly",
            "static",
            "abstract",
            "virtual",
            "dependentName",
            "defaultLibrary",
            "usedAsMutableReference",
            "usedAsMutablePointer",
            "constructorOrDestructor",
            "userDefined",
            "functionScope",
            "classScope",
            "fileScope",
            "globalScope"
          ],
          "tokenTypes": [
            "variable",
            "variable",
            "parameter",
            "function",
            "method",
            "function",
            "property",
            "variable",
            "class",
            "interface",
            "enum",
            "enumMember",
            "type",
            "type",
            "unknown",
            "namespace",
            "typeParameter",
            "concept",
            "type",
            "macro",
            "modifier",
            "operator",
            "comment"
          ]
        },
        "range": false
      },
      "signatureHelpProvider": {
        "triggerCharacters": [
          "(",
          ")",
          "{",
          "}",
          "<",
          ">",
          ","
        ]
      },
      "standardTypeHierarchyProvider": true,
      "textDocumentSync": {
        "change": 2,
        "openClose": true,
        "save": true
      },
      "typeDefinitionProvider": true,
      "typeHierarchyProvider": true,
      "workspaceSymbolProvider": true
    },
    "serverInfo": {
      "name": "clangd",
      "version": "clangd version 16.0.2 (https://github.com/llvm/llvm-project 18ddebe1a1a9bde349441631365f0472e9693520) linux+grpc x86_64-unknown-linux-gnu"
    }
  }
}

[Error - 9:12:45 PM] Server initialization failed.
Error: command 'clangd.applyFix' already exists
	at e.$vL.registerCommand (/home/shiyao/.vscode-server/bin/2ccd690cbff1569e4a83d7c43d45101f817401dc/out/vs/workbench/api/node/extensionHostProcess.js:100:62663)
	at Object.registerCommand (/home/shiyao/.vscode-server/bin/2ccd690cbff1569e4a83d7c43d45101f817401dc/out/vs/workbench/api/node/extensionHostProcess.js:118:20174)
	at x1.register (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:37:71984)
	at x1.initialize (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:37:71547)
	at ff.initializeFeatures (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:19266)
	at ff.doInitialize (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:7616)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async ff.start (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:4636)
[Error - 9:12:45 PM] Clang Language Server client: couldn't create connection to server.
Error: command 'clangd.applyFix' already exists
	at e.$vL.registerCommand (/home/shiyao/.vscode-server/bin/2ccd690cbff1569e4a83d7c43d45101f817401dc/out/vs/workbench/api/node/extensionHostProcess.js:100:62663)
	at Object.registerCommand (/home/shiyao/.vscode-server/bin/2ccd690cbff1569e4a83d7c43d45101f817401dc/out/vs/workbench/api/node/extensionHostProcess.js:118:20174)
	at x1.register (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:37:71984)
	at x1.initialize (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:37:71547)
	at ff.initializeFeatures (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:19266)
	at ff.doInitialize (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:7616)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async ff.start (/home/shiyao/.vscode-server/extensions/llvm-vs-code-extensions.vscode-clangd-0.1.24/out/bundle.js:39:4636)
V[21:12:45.385] <<< {
  "jsonrpc": "2.0",
  "method": "initialized",
  "params": {}
}

I[21:12:45.385] <-- initialized
V[21:12:45.390] <<< {
  "jsonrpc": "2.0",
  "method": "initialized",
  "params": {}
}

I[21:12:45.390] <-- initialized
V[21:12:45.405] <<< {
  "id": 1,
  "jsonrpc": "2.0",
  "method": "shutdown"
}

I[21:12:45.406] <-- shutdown(1)
I[21:12:45.406] --> reply:shutdown(1) 0 ms
V[21:12:45.406] >>> {
  "id": 1,
  "jsonrpc": "2.0",
  "result": null
}

V[21:12:45.406] <<< {
  "jsonrpc": "2.0",
  "method": "exit"
}

I[21:12:45.406] <-- exit
I[21:12:45.406] LSP finished, exiting with status 0
```

**Comment by gotlibsh** [comment]
any update on this? facing similar issues...

**Comment by HighCommander4** [comment]
> any update on this? facing similar issues...

Does "Reload Window" fix it?

**Comment by kotborealis** [comment]
Does anyone have any idea how to fix it? :)
I'm eager to take a look into it myself, so any suggestions are appreciated.

**Comment by HighCommander4** [comment]
> Does anyone have any idea how to fix it? :)

Just to make sure I'm understanding correctly, repeating my question above: does "Reload Window" fix this?

And also to double check, does this from the issue description apply in your case as well:

> **edit**: This only happens when clangd is not started (no source code file is open) and the server is restarted.

**Comment by ToBoMi** [comment]
I checked again today.
It happens (at least) when

* no source file is open (C/C++) _since the start of vscode_ and 
* the language server is restarted _in that session_ through the gui (why should one do that? - fair enough - [1]).

It cannot be suppressed by

* opening a source file _in that same session_ and
* restarting the language server through the gui command (_even if there is an open source file the issue occurs and can be reproduced repeatedly_)

It can be circumvented by

* `reload window` _while keeping the recently opened source file open_ and
* then restarting the language server _in that new session_ succeeds

[1] I copy the compile commands to the project root manually after build. I have a multi root environment where multple folders are build through vscode tasks in two different build configurations. After each build I automatically copy the compile commands from the folder they are build into the respectie project root, to make them discoverable by clangd. I automatically clean the clangd cache after the build and restart the language server. Sometimes when that happens there is no source file open. That triggers the issue. Maybe we should talk about that and how to use clangd in such a scenario.

**Comment by kotborealis** [comment]
> > Does anyone have any idea how to fix it? :)
> 
> Just to make sure I'm understanding correctly, repeating my question above: does "Reload Window" fix this?
> 
> And also to double check, does this from the issue description apply in your case as well:
> 
> > **edit**: This only happens when clangd is not started (no source code file is open) and the server is restarted.

Yes, "Reload window" fixes it, but it's not a perfect solution :)

**Comment by HighCommander4** [comment]
Thanks for the details. I didn't realize that explicitly restarting clangd was a regular part of some workflows (I've only ever done that for debugging purposes, e.g. to restart clangd after a crash or to switch to a different clangd version after modifying `"clangd.path"`).

**Comment by HighCommander4** [comment]
> I checked again today. It happens (at least) when
> 
>    * no source file is open (C/C++) _since the start of vscode_ and
>    * the language server is restarted _in that session_ through the gui (why should one do that? - fair enough - [1]).

VSCode only starts the language server to begin with when a file whose file type is registered to be associated with the language server is opened for the first time.

So, in the situation where no C/C++ source file is open since the launch of VSCode, the language server is not running to begin with.

The root of the issue then is that the "clangd: restart language server" command does not expect this situation (it expects clangd to be already running). We should get it to handle this situation gracefully (i.e. to act as just "**start** language server" if the language server isn't already running).

**Comment by ToBoMi** [comment]
> I didn't realize that explicitly restarting clangd was a regular part of some workflows

And maybe it don't nessecarily have to. Perhaps you can point out how to handle different build configurations.
When I change the build configuration, containing another platform for example, should the clangd cache be cleared and the server be restarted?
There are issues regarding multi root workspaces. Maybe this is not supported currently.

> VSCode only starts the language server to begin with when a file whose file type is registered to be associated with the language server is opened for the first time.

> We should get it to handle this situation gracefully (i.e. to act as just "**start** language server" if the language server isn't already running).

Does it make sense to start it, when there is no source file open?

**Comment by kotborealis** [comment]
> And maybe it don't nessecarily have to. Perhaps you can point out how to handle different build configurations.

This would be great! 

To explain further - my extension manages different platforms/SDKs and build configurations. This requires it to update clangd config - specify new paths for clangd binary, new compile commands dir, `query-driver` argument and so on.

![image](https://github.com/clangd/vscode-clangd/assets/6463851/feb5a895-8e97-4a1c-8d50-a82c79186619)

**Comment by HighCommander4** [comment]
> > VSCode only starts the language server to begin with when a file whose file type is registered to be associated with the language server is opened for the first time.
> 
> > We should get it to handle this situation gracefully (i.e. to act as just "**start** language server" if the language server isn't already running).
> 
> Does it make sense to start it, when there is no source file open?

I would say yes. There are operations the language server supports that don't require an open file.

An example would be `workspace/symbol`. A user might want to open their first file based on the name of a class or function it contains (looked up using `workspace/symbol`), rather than using the file name.

**Comment by HighCommander4** [comment]
Regarding build configurations, I would suggest taking that discussion to a dedicated issue for visibility.

**Comment by HighCommander4** [comment]
I've debugged a bit what's going on here.

The first thing to note is that the `clangd.restart` command is registered when the extension is activated (normally triggered by opening a C/C++ source file). So, how is it even possible to call it when the extension is not yet activated?

The answer seems to be that, since the command is declared in the extension's `package.json`, vscode knows about it, and internally registers it (e.g. such that it shows up in the Command Palette) even without the extension being activated. When it's invoked, if the extension hasn't been activated, then vscode first activates the extension (allowing it to register the handler for the command), and then executes the handler.

So, in principle, calling `clangd.restart` when the extension is not yet activated should result in the extension being activated (which also starts the server), then running the handler (which stops the just-started server and starts it again).

However, it seems that vscode runs the handler "too soon" after activating the extension for the above sequence to actually succeed. At the time the handler is invoked, the `LanguageClient` is still in the `Starting` state, and our attempt to stop it triggers an exception (`Error: Client is not running and can't be stopped. It's current state is: starting`), and things go downhill from there (the rest of the cleanup code doesn't run, and then trying to start things without having cleaned up properly we end up trying to do things like register commands twice).

**Comment by HighCommander4** [comment]
Doing a start/stop/start sequence seems pointless/wasteful, so I'm thinking the fix should be to detect the case where `clangd.restart` just activated the extension, and have the handler be a no-op in that case.

**Comment by HighCommander4** [comment]
Proposed fix: https://github.com/clangd/vscode-clangd/pull/587

**Comment by HighCommander4** [comment]
> > Does it make sense to start it, when there is no source file open?
> 
> I would say yes. There are operations the language server supports that don't require an open file.
> 
> An example would be `workspace/symbol`. A user might want to open their first file based on the name of a class or function it contains (looked up using `workspace/symbol`), rather than using the file name.

This is an aside, but mentioning for completeness: the workflow I described here involving `workspace/symbol` doesn't actually work today, because clangd doesn't load the project's index until a source file is opened. (See https://github.com/clangd/clangd/discussions/1341.)

However, I view that as a limitation to be fixed in clangd (at least in some configurations), and overall I still think the less surprising behaviour is for "clangd: restart language server" to consistently result in a state where the language server is running.
